### ISSUE TITLE
xxd启动失败

### ISSUE THREAD

**Issue by Zyx-A** [easysoft/xuanxuan#10]
cd /opt
tar xf ranzhi.4.4.stable.zbox_64.tar.gz
cd zbox
./zbox start
Apache is running
Mysql is running

cd /opt/xxd-1.1.1-linux-x64
cat config/xxd.conf 
======================================================================
[server]
# 监听的服务器ip地址
ip=172.16.22.131

# 与聊天客户端通讯的端口
chatPort=11444

# 通用端口，该端口用于客户端登录时验证，以及文件上传下载使用
commonPort=11443

# 上传文件的保存路径，最后的“/”不能省略，表示路径
uploadPath=tmpfile/

# 上传文件的大小，支持：K,M,G
uploadFileSize=32M

[ranzhi]
# xuanxuan和ranzhiName是自定义然之服务器名称，客户端登录时需要
# token从然之服务器中获取，长度为32个字符
# 设置某个服务器为default后，客户端省略服务器名称时默认使用default
# 地址格式为http[s]://addr/path/xuanxuan.php,token[,default]
# ranzhiName=http[s]://ip:port/xuanxuan.php,tokenID8888888888888888888888888
xuanxuan=http://172.16.22.131:80/xuanxuan.php,88888888888888888888888888888888,default

# NOTE: Windows accept / as path separator.
[log]
# 程序运行日志的保存路径
logPath=log/

[certificate]
# 证书的保存路径，默认情况下xxd会生成自签名证书
crtPath=certificate/
=========================================================
./xxd 
sys start,version:V1.1.1, server test model is false
ProgramName:xxd,System:linux-amd64
ranzhi server login error

xxd服务始终启动失败。教程中出现的8188端口，ss -lntu 查找后，该端口并没有被监听。
访问 http://172.16.22.131/xuanxuan.php，提示404，find能找到xuanxuan.php
find . -name xuanxuan.php
./app/ranzhi/app/oa/attend/ext/lang/zh-cn/xuanxuan.php
./app/ranzhi/app/oa/attend/ext/lang/en/xuanxuan.php
./app/ranzhi/app/oa/attend/ext/lang/zh-tw/xuanxuan.php
./app/ranzhi/app/sys/user/ext/model/xuanxuan.php
./app/ranzhi/app/sys/upgrade/ext/config/xuanxuan.php
./app/ranzhi/app/sys/setting/ext/control/xuanxuan.php
./app/ranzhi/app/sys/install/ext/model/xuanxuan.php
./app/ranzhi/app/sys/common/ext/lang/zh-cn/xuanxuan.php
./app/ranzhi/app/sys/common/ext/lang/en/xuanxuan.php
./app/ranzhi/app/sys/common/ext/lang/zh-tw/xuanxuan.php
./app/ranzhi/config/ext/xuanxuan.php
./app/ranzhi/www/xuanxuan.php

请问怎么解决？

**Comment by riverdream** [comment]
xxd服务器提示登录然之服务器失败。
1、请确认然之是否能够登录成功。
2、请确认然之配文件，http://172.16.22.131/ranzhi/xuanxuan.php 是否少一层路径。
3、请确认端口号是否正确。如：http://172.16.22.131:8080/ranzhi/xuanxuan.php

**Comment by Zyx-A** [comment]
1、第一步使用 admin/123456 成功登录

2、第二步报错：
Fatal error: Uncaught LengthException: The ciphertext has an invalid padding length (0) compared to the block size (16) in /opt/zbox/app/ranzhi/lib/phpaes/phpseclib/Crypt/Common/SymmetricKey.php:1989 Stack trace: #0 /opt/zbox/app/ranzhi/lib/phpaes/phpseclib/Crypt/Common/SymmetricKey.php(1255): SymmetricKey->unpad(false) #1 /opt/zbox/app/ranzhi/lib/phpaes/phpaes.class.php(33): SymmetricKey->decrypt('') #2 /opt/zbox/app/ranzhi/framework/xuanxuan.class.php(302): phpAES->decrypt('') #3 /opt/zbox/app/ranzhi/framework/xuanxuan.class.php(120): xuanxuan->decrypt('') #4 /opt/zbox/app/ranzhi/www/xuanxuan.php(25): xuanxuan->parseRequest() #5 {main} thrown in /opt/zbox/app/ranzhi/lib/phpaes/phpseclib/Crypt/Common/SymmetricKey.php on line 1989

3、第三步，端口是默认的80端口，没做修改。

**Comment by fireware** [comment]
xuan.im官网有我们的群号，可以加群讨论一下。看样子是然之解密出现问题

**Comment by catouse** [comment]
应该是一键安装包开启了访问控制导致。
