### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by wulunyi** [easysoft/xuanxuan#11]
部分配置文件在 app 下并不存在
![image](https://user-images.githubusercontent.com/15170275/29309107-e70a483a-81da-11e7-89d3-b902a163b61d.png)

**Comment by wulunyi** [comment]
1ed48c3e3f9d284c543c586186b4c38bd09d7b05 这次提交这些文件是存在的

**Comment by catouse** [comment]
如果你要定制使用 v1.1.1 的代码，最近的提交可能都不稳定。
