### ISSUE TITLE
客户端Role不能动态显示

### ISSUE THREAD

**Issue by weijer** [easysoft/xuanxuan#2]
问题描述：然之后台Role是可以自定义改变的，现在客户端是根据然之默认角色写死的。

建议：直接显示role字符串就行，这个数据后台去动态处理！

**Comment by Catouse** [comment]
我们已有计划会增强组织成员管理功能，会增加自定义角色及按部门查看功能。

**Comment by raindylong** [comment]
xuanxuan很好用，暂时发现一个问题描述如下：
（1）用户A已经xuanxuan在线，在然之后台增加新用户B
（2）B用户登录xuanxuan后，A用户看到是的B只有一个代号“用户-ID号”
（3）只有A在退出重新登录后，才能fresh到B的正确信息

需要在xxd上增加定时fresh userlist给全部客户端？
谢谢。

**Comment by catouse** [comment]
部门和角色现在可以动态显示了。
