### ISSUE TITLE
login client error .

### ISSUE THREAD

**Issue by jeffycai** [easysoft/xuanxuan#20]
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Navbar

![qq 20171119175038](https://user-images.githubusercontent.com/4546658/32989499-66957288-cd52-11e7-9d8c-d7b76844ca70.png)

**Comment by catouse** [comment]
此问题现在应该不存在了吧？

**Comment by jeffycai** [comment]
还是存在的，我用的是最新的版本。

**Comment by catouse** [comment]
确定使用的是最新的代码？

**Comment by catouse** [comment]
你用这个文件 https://github.com/easysoft/xuanxuan/blob/master/app/views/main/navbar.js 对比下本地的 navbar.js 文件。
