### ISSUE TITLE
xxd服务器端存储能设置对象存储么？或者能指定路径么？

### ISSUE THREAD

**Issue by zhanggaoxuan** [easysoft/xuanxuan#25]
xxd服务器端存储能设置对象存储么？或者能指定路径么？

**Comment by zhanggaoxuan** [comment]
如果可以设置存储的话，就可以方便把用户发送的图片，文件实现云同步了，也能实现聊天记录漫游

**Comment by catouse** [comment]
```conf

**Comment by catouse** [comment]
喧喧的聊天记录和文件图片都是在云端的，你随时可以通过客户端的消息记录管理同步功能进行同步。

用户上传的图片和文件都在 xxd 所在都服务器上，你可以通过 xxd 配置文件 xxd.conf 中的 uploadPath 设置文件保存都目录。

```conf
# 上传文件的保存路径，最后的“/”不能省略，表示路径
# 注意：Windows 下路径中的 ‘\’ 需要转义写成 ‘\\’，例如 ‘D:\xxd\files’ 要写成 ‘D:\\xxd\\files’
uploadPath=tmpfile/
```

因为是用法问题，这个 Issue 先关闭了。
