### ISSUE TITLE
喧喧Windows XSS bug

### ISSUE THREAD

**Issue by dongdong1972** [easysoft/xuanxuan#32]
type `<img src=x onerror=alert(1)>` on windows v1.6.0

**Comment by dongdong1972** [comment]
暂行解决方案：
1.从`im_chat`,`im_message`表删除相应聊天群。即可解决储存型XSS。
2.解决相关人员。

**Comment by catouse** [comment]
请问用的是开发版吗？1.6正式版中应该是不能直接发送html标签的
