### ISSUE TITLE
请问服务器端是开源的吗？

### ISSUE THREAD

**Issue by wpdev01** [easysoft/xuanxuan#38]
谢谢。

**Comment by catouse** [comment]
服务器端和客户端都是开源的。项目源码目录概要说明：

<table>
  <thead>
    <tr>
      <th>目录</th>
      <th>介绍</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>/xxc/</code></td>
      <td>客户端项目</td>
    </tr>
    <tr>
      <td><code>/xxc/app/</code></td>
      <td>客户端源代码</td>
    </tr>
    <tr>
      <td><code>/xxc/app/assets/</code></td>
      <td>客户端使用到的第三发静态资源目录</td>
    </tr>
    <tr>
      <td><code>/xxc/app/media/</code></td>
      <td>客户端上用到的图片、语音及表情资源</td>
    </tr>
    <tr>
      <td><code>/xxc/app/lang/</code></td>
      <td>客户端语言配置文件目录，目前只有中文简体文件 `zh-cn.json</td></td>
    </tr>
    <tr>
      <td><code>/xxc/app/style/</code></td>
      <td>客户端界面样式表文件目录，通常为 Less 文件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/utils/</code></td>
      <td>客户端用到的工具组件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/network/</code></td>
      <td>客户端内部与网络相关的接口模块</td>
    </tr>
    <tr>
      <td><code>/xxc/app/config/</code></td>
      <td>客户端配置文件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/platform</code></td>
      <td>客户端与平台相关的模块</td>
    </tr>
    <tr>
      <td><code>/xxc/app/core/</code></td>
      <td>客户端核心模块</td>
    </tr>
    <tr>
      <td><code>/xxc/app/components/</code></td>
      <td>客户端界面用到的通用 React 组件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/views/</code></td>
      <td>客户端界面 React 视图组件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/main.development.js</code></td>
      <td>Electron 入口文件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/index.html</code></td>
      <td>主窗口 HTML 代码文件</td>
    </tr>
    <tr>
      <td><code>/xxc/app/index.js</code></td>
      <td>Electron 主窗口入口代码文件</td>
    </tr>
    <tr>
      <td><code>/xxc/resources/</code></td>
      <td>Electron 打包时用到的资源文件目录</td>
    </tr>
    <tr>
      <td><code>/xxc/build/</code></td>
      <td>Webpack 配置文件，开发模式脚本以及 Electron 安装包构建相关脚本</td>
    </tr>
    <tr>
      <td><code>/xxb/</code></td>
      <td>后端服务器源代码目录</td>
    </tr>
    <tr>
      <td><code>/xxd/</code></td>
      <td>XXD 中间服务器端源代码目录</td>
    </tr>
    <tr>
      <td><code>/ranzhi</code></td>
      <td>然之协同服务器端扩展源代码目录</td>
    </tr>
  </tbody>
</table>
