### ISSUE TITLE
下载的客户端的聊天日志存放位置在哪里呢？

### ISSUE THREAD

**Issue by lgarfield** [easysoft/xuanxuan#44]
清空了数据库上面的记录，但是本地客户端打开依然能看到记录。

如何将其完全清空呢？

**Comment by catouse** [comment]
目前界面上没有提供手动清除本地数据库的入口。如果使用的是开发版客户端，则可以登录之后在控制台输入如下命令来删除本地数据库：
```js
Xext.app.db.database._db.delete();
```
