### ISSUE TITLE
打包后图标可以替换吗？我替换了好像就打包不出来了，如何生成？

### ISSUE THREAD

**Issue by simcyber** [easysoft/xuanxuan#50]
打包后图标可以替换吗？我替换了好像就打包不出来了，如何生成？

**Comment by catouse** [comment]
请注意：喧喧使用 [MIT 开源许可协议](https://github.com/easysoft/xuanxuan/blob/master/LICENSE)，更改应用名称以及登录界面和关于界面上的 LOGO 图像需要取得我们的授权，详情请阅读   [官方网站定制开发页面](https://xuan.im/page/dingzhikaifa.html)。如果仅仅是更改界面配色以及显示的语言文本，或者关闭某些功能则不需要获取我们的授权。

**Comment by easysoft** [comment]
浩哥写错了，喧喧使用的是ZPL协议。http://zpl.pub

**Comment by simcyber** [comment]
好，知道了，谢谢！那就不改了。
