### ISSUE TITLE
上传大文件报错

### ISSUE THREAD

**Issue by helloexp** [easysoft/xuanxuan#54]
![default](https://user-images.githubusercontent.com/21156949/53543748-b1f37d80-3b5e-11e9-95a7-962ba675176c.png)

其中lnmp一键安装的php环境
另外php.ini何nginx.conf上传配置文件 都修改为500M，但是上传90M就报错

**Comment by easysoft** [comment]
上传文件不是走的php，是在xxd里面的。应该是内存超了。

**Comment by catouse** [comment]
目前上传文件使用 http 形式上传到 XXD，并且不支持断点续传，所以不是为上传大文件而设计，可以关注我们后续的上传大文件方案。
