### ISSUE TITLE
禅道客户端在mac 上command + Q  的功能无法修改

### ISSUE THREAD

**Issue by MrLaibin** [easysoft/xuanxuan#55]
如果将command+q选择一类操作后无法修改。比如像恢复默认
![image](https://user-images.githubusercontent.com/13825960/54097861-00b9d680-43ed-11e9-84b0-9c5d0425cff7.png)

**Comment by catouse** [comment]
你可以在个人设置对话框中修改。
![image](https://user-images.githubusercontent.com/472425/54112224-a5094080-4420-11e9-912b-5e90d55ec2bd.png)

**Comment by MrLaibin** [comment]
谢谢，刚刚试了一下，的确可以。有个建议，关闭窗口等于最小化。
