### ISSUE TITLE
升级到新版后无法私聊,但可以群聊

### ISSUE THREAD

**Issue by ktsleep** [easysoft/xuanxuan#58]
{
    "module":"chat",
    "method":"message",
    "result":"fail",
    "message":"无法向与您无关的会话发送消息。",
    "rid":"",
    "lang":"zh-cn",
    "v":"2.5.5"
}

**Comment by easysoft** [comment]
版本不兼容。请用我们网站最新的2.5.6系列的版本。

**Comment by catouse** [comment]
确保客户端版本大于或同于服务器端版本，服务器端 XXD 和 XXB 版本必须一致。
