### ISSUE TITLE
允许创建相同成员的讨论组？

### ISSUE THREAD

**Issue by tt244213968** [easysoft/xuanxuan#8]
多次创建相同成员的讨论组，系统没有报错，还是说作者您就是这么设计的？嘿嘿。。。

**Comment by Catouse** [comment]
这个是系统允许的行为。讨论组是以主题为中心，成员是动态的，随时会添加或减少成员。

**Comment by tt244213968** [comment]
那么主题现在可以自定义么？数据库字段subject都为0呀

**Comment by Catouse** [comment]
@tt244213968 这里所指的主题是讨论组主题，subject 为以后关联其他数据使用。
