### ISSUE TITLE
腾讯云无法监听到ip

### ISSUE THREAD

**Issue by ychost** [easysoft/xuanxuan#9]
腾讯云主机 ifconfig 只出现内网ip，所以只能监听内网，无法监听到外网ip 考虑用ngnix代理但是，用http代理到https好像失败了

**Comment by easysoft** [comment]
监听内网也没关系的。现在很多云主机环境都是这样的。我们用的青云机器也是这样的，但可以正常监听的。只要网络请求能够进来就行。建议你咨询下腾讯云的支持。腾讯云我们没有用。

**Comment by riverdream** [comment]
监听内网IP地址就可以了。实际上你服务器中开启的httpd或者其它服务，监听的都是内网的地址。

**Comment by ychost** [comment]
必须申请ssl证书才可以吗

**Comment by ychost** [comment]
必须申请ssl证书才可以吗

**Comment by riverdream** [comment]
xxd是不需要去申请证书的，启动的时候会自己创建一个自签名的证书。
你可以查看与xxd同级目录下的certificate目录，你启动一次后该目录下会有证书生成。

**Comment by ychost** [comment]
搞定了防火墙原因不好意思，疏忽这个了
